spring.application.name=ms-envio
server.port=${PORT:8086}

spring.datasource.url=jdbc:mysql://localhost:3306/ms_envio_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ms.pedido.url=http://localhost:8083/api/pedidos
