spring.application.name=ms-opinion
server.port=${PORT:8088}

spring.datasource.url=jdbc:mysql://localhost:3306/ms_opinion_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ms.cliente.url=http://localhost:8082/api/clientes
ms.producto.url=http://localhost:8080/api/productos
