spring.application.name=ms-notificacion
server.port=${PORT:8089}

# Conexion a MySQL (Laragon) - base de datos propia de este microservicio
spring.datasource.url=jdbc:mysql://localhost:3306/ms_notificacion_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL donde vive ms-cliente, para poder consultarlo por WebClient
ms.cliente.url=http://localhost:8082/api/clientes
