spring.application.name=primer-proyecto

# Conexion a MySQL (Laragon)
spring.datasource.url=jdbc:mysql://localhost:3306/primer_proyecto_db
spring.datasource.username=root
spring.datasource.password=

# Hibernate crea/actualiza las tablas automaticamente segun tus entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
